version: "3.7"
services:
  laravelsrv:
    user: nginx
    build:      
      args:
        user: nginx
        uid: 994
      context: .
      dockerfile: Dockerfile
    image: amsaravi/textograph-server
    container_name: textograph-app
    restart: unless-stopped
    working_dir: /var/www/html
    # volumes:
    #    - ./database.php:/var/www/html/config/database.php