version: "3.7"
services:
  laravelsrv:    
    ports:
        - 8400:9000
        - 8100:8000
    environment: 
        - DB_CONNECTION=mysql
        - DB_HOST=192.168.1.10
        - DB_PORT=3306
        - DB_DATABASE=test_12
        ## uncomment these lines just for developement purpose
        # - DB_USERNAME=your-db-user
        # - DB_PASSWORD=your-db-user-pass
        - DB_USERNAME_FILE=mysql_user
        - DB_PASSWORD_FILE=mysql_pass
    secrets:
        - mysql_pass
        - mysql_user
# put your secrets in these two files just for developement purpose
secrets:    
    mysql_pass:
        file: mysql_fake_pass.txt
    mysql_user:
        file: mysql_fake_user.txt